### ISSUE TITLE
解决

### ISSUE THREAD

**Issue by kwucheuwkzbAks** [AppleClash/App#11]

**Comment by kwucheuwkzbAks** [comment]
或者 一样的配置名字 不能再加

**Comment by Arror** [comment]
> 或者 一样的配置名字 不能再加

iPhone 侧滑删除（可能会改成长按）
Mac 右键 -> 删除

**Comment by kwucheuwkzbAks** [comment]
没打算加个全删的技能吗

**Comment by Arror** [comment]
> 没打算加个全删的技能吗

倒是没难度，只是觉得没有必要

**Comment by kwucheuwkzbAks** [comment]
> > 没打算加个全删的技能吗
> 
> 倒是没难度，只是觉得没有必要

还有一个idea就是加配置之后自动选择最新的配置

**Comment by Arror** [comment]
> > > 没打算加个全删的技能吗
> > 
> > 
> > 倒是没难度，只是觉得没有必要
> 
> 还有一个idea就是加配置之后自动选择最新的配置

这个可以，一行代码就可以解决，在添加配置后把currentUUIDString设置成新添加配置uuid的即可

**Comment by kwucheuwkzbAks** [comment]
configlistview？ 还是 nsmanager context？

**Comment by Arror** [comment]
NSManagedObjectContext+File.swift文件中importClashConfig方法
```swift
try self.save()

// 设置配置为当前添加的配置
UserDefaults.shared.set(uuid.uuidString, forKey: Clash.currentConfigUUID)
```
