### ISSUE TITLE
tunnelFileDescriptor 问题，这个应该是给t2socks传递数据包的，为什么要在两个类写两个一样的方法

### ISSUE THREAD

**Issue by aishuidedabai** [AppleClash/App#12]
PacketTunnelProvider+ClashKit 和PacketTunnelProvider

**Comment by aishuidedabai** [comment]
有两个小疑问

1 t2socks可以自由拓展到其他项目吗，我看到它的核心是读取fd数据，转为socks协议。再由clashkit监听8080端口，连接上对应的协议将socks数据发出去。
2 不用t2socks可以吗，直接把fd数据发给clashkit，本身那些trojan之类的协议就可以把fd转为tcp协议，所以用t2socks意义是啥？

**Comment by Arror** [comment]
> 有两个小疑问
> 
> 1 t2socks可以自由拓展到其他项目吗，我看到它的核心是读取fd数据，转为socks协议。再由clashkit监听8080端口，连接上对应的协议将socks数据发出去。 2 不用t2socks可以吗，直接把fd数据发给clashkit，本身那些trojan之类的协议就可以把fd转为tcp协议，所以用t2socks意义是啥？

1 理论上可以扩展到其他项目。
2 clash的开源版本不支持tun模式，所以NEPacketTunnelProvider中不遵守系统代理的流量无法被clash处理，需要T2S转换。

Trojan只是clash支持的协议之一，不直接处理流量，而是由clash进行调度分发。

**Comment by aishuidedabai** [comment]
感谢你的指导，系统代理的流量就三种吧http和TCP，UDP。
您这里的的t2socks将所有的TCP和UDP都转为了socks协议吗，您写了hasPrefix("utun")这个方法，那我拿掉的话是不是可以更高效一些，将所有的fd都交给t2socks处理，clashkit只要开启本地socks代理，并且监听socks的端口，就可以将所有的流量交给各种协议传送

另外问一下，ipv6支持吗

**Comment by Arror** [comment]
> 感谢你的指导，系统代理的流量就三种吧http和TCP，UDP。 您这里的的t2socks将所有的TCP和UDP都转为了socks协议吗，您写了hasPrefix("utun")这个方法，那我拿掉的话是不是可以更高效一些，将所有的fd都交给t2socks处理，clashkit只要开启本地socks代理，并且监听socks的端口，就可以将所有的流量交给各种协议传送
> 
> 另外问一下，ipv6支持吗

TunnelProvider可以直接转发的流量只有遵守代理的HTTP、HTTPS流量。
获取FD的方法是我抄来的，去掉后面的判断，我不清楚会不会有什么问题。
一般情况下，大部分的流量都是遵守代理的HTTP、HTTPS流量，系统可以直接转发到clash的本地HTTP inbound，都交给t2s反而更低效吧？

**Comment by aishuidedabai** [comment]
分流已经很完美了，但是打开网易云音乐就会断开，QQ音乐就无问题，加了网易的规则也没用，clashkit产生了Clash

**Comment by Arror** [comment]
> 分流已经很完美了，但是打开网易云音乐就会断开，QQ音乐就无问题，加了网易的规则也没用，clashkit产生了Clash

有clash输出的日志和崩溃日志么？

**Comment by aishuidedabai** [comment]
我建议还是 去掉这个，&& String(cString: buf).hasPrefix("utun")。我看日志的时候有些流量没处理好，直接拥堵crash了，去掉这句话可以保证fd的统一性，不会出现意外情况，而且也没多浪费性能

**Comment by Arror** [comment]
> 我建议还是 去掉这个，&& String(cString: buf).hasPrefix("utun")。我看日志的时候有些流量没处理好，直接拥堵crash了，去掉这句话可以保证fd的统一性，不会出现意外情况，而且也没多浪费性能

"可以保证fd的统一性，不会出现意外情况"

可以详细说明一下么？

**Comment by aishuidedabai** [comment]
主要我也不是很熟悉fd，我看有些app，主要是TCP流那些，貌似自己修改了数据类型，导致不满足处理的条件，这个时候就会拥堵crash，内存瞬间爆炸，当我去掉hasPrefix("utun")就平稳运行了
