### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kwucheuwkzbAks** [AppleClash/App#13]
Clash 链接VPN之后 把clash软件关了从新打开软件 显示连接中 可是打开safari看看 已经vpn功能没有了

**Comment by Arror** [comment]
> Clash 链接VPN之后 把clash软件关了从新打开软件 显示连接中 可是打开safari看看 已经vpn功能没有了

XCode重新编译运行么？

**Comment by kwucheuwkzbAks** [comment]
> 

啥意思？？

**Comment by Arror** [comment]
> 啥意思？？

在设置中把日志等级 设置为 “信息”，打开控制台App，日志过滤条件为PacketTunnel进程，重现问题后，查看是否有日志输出？

**Comment by kwucheuwkzbAks** [comment]
就是 开着vpn关了Clash 然后 再打开 
VPNStatus .connected 状态 ： isOn true
上面显示 VPN标记 好像 clash技能冲突了 

开着vpn 关软件 正常使用 再打开 就要关vpn 然后要从新开才可以用

**Comment by Arror** [comment]
> 就是 开着vpn关了Clash 然后 再打开 VPNStatus .connected 状态 ： isOn true 上面显示 VPN标记 好像 clash技能冲突了
> 
> 开着vpn 关软件 正常使用 再打开 就要关vpn 然后要从新开才可以用

我这没能重现。

启动VPN，杀掉App，然后重新打开App，这个时候 系统设置 -》VPN 中 Clash 是否处于连接状态？

还有，你用的是main最新的提交构建的么？如果不是，用的是哪个提交？iOS系统版本是多少？我这边再尝试重现一下。

**Comment by kwucheuwkzbAks** [comment]
ios 15 用的是 configyaml 弄之前的那个 5天前的

**Comment by Arror** [comment]
> ios 15 用的是 configyaml 弄之前的那个 5天前的

使用最新提交构建试试
