### ISSUE TITLE
T2SKit

### ISSUE THREAD

**Issue by aishuidedabai** [AppleClash/App#14]
请问你的 T2SKit 怎么编译的，leaf我已经安装好，但是我不知道怎么编译为一个T2SKit库

**Comment by Arror** [comment]
安装好Rust环境，安装rust-lipo，安装iOS，macOS对应的各个target，参考https://github.com/AppleClash/tun2socks/blob/tun2socks_dev/Makefile里面xcframework命令构建xcframework，然后结合导出的头文件，创建Package。

**Comment by aishuidedabai** [comment]
感谢，      "outbounds": [ ，
                    "tag": "aaaa"
                }
我成功编译了，这个tag只是标识吧，我改成其他也没问题，研究了一下，大致都搞明白了，clashkit监听了socks端口，其实我主要是想要一个t2，有了它才能让数据流通起来，不然拿一个fd真不知道咋办
