### ISSUE TITLE
接入 leaf 后，配置文件打算怎么对应？

### ISSUE THREAD

**Issue by CreatorMetaSky** [AppleClash/App#7]
1. 从 rust 入手，支持 clash 的配置格式
2. 从 app 或者 network extension 层，动态转换 clash 配置到 leaf 配置

你是怎么考虑的？

**Comment by Arror** [comment]
> 1. 从 rust 入手，支持 clash 的配置格式
> 2. 从 app 或者 network extension 层，动态转换 clash 配置到 leaf 配置
> 
> 你是怎么考虑的？

配置还是用clash的配置，leaf只用来做tun2socks，把tun流量发送给clash处理。

顺带问一下，你知道怎么用rust生成的.a静态库创建xcframework么？需要支持iOS，iOS x86_x64、arm模拟器，macOS x86_x64、arm。

**Comment by CreatorMetaSky** [comment]
那 leaf 跟 clash 是传递数据流，是走 API 还是走 socket 协议？
还有如果 rust 和 go 之间互相调用，go 那边不见得没有内存问题，感觉也是坑。

**Comment by CreatorMetaSky** [comment]
👌🏻，期待大神的成果。

**Comment by Arror** [comment]
Ref: https://github.com/AppleClash/T2SKit
