### ISSUE TITLE
启动没反应

### ISSUE THREAD

**Issue by taojishou** [AppleClash/App#8]
点启动好像没反应？是缺什么吗

**Comment by Arror** [comment]
> 点启动好像没反应？是缺什么吗

请提供具体描述、截图以及日志。
日志获取方式：设置里日志等级设置为信息，连接Mac，在控制台App中获取。

**Comment by taojishou** [comment]
好像修复了，我在看看

**Comment by taojishou** [comment]
大佬，现在tun2socks换成了leaf了吗？似乎现在的全局不起作用

**Comment by Arror** [comment]
> 大佬，现在tun2socks换成了leaf了吗？似乎现在的全局不起作用

已经替换为leaf的实现了。
全局模式默认走了DIRECT策略。这部分在策略组里没体现出来。我看看怎么处理吧。

**Comment by Arror** [comment]
> 大佬，现在tun2socks换成了leaf了吗？似乎现在的全局不起作用

已修复全局无效问题。

**Comment by taojishou** [comment]
点赞

**Comment by Arror** [comment]
> 点赞

欢迎PR。

**Comment by taojishou** [comment]
好的，ios也ok的吧

**Comment by Arror** [comment]
> 好的，mac端也ok的吧

Mac的还没加Global策略组，UI考虑重新设计。
