### ISSUE TITLE
来求助了……

### ISSUE THREAD

**Issue by aishuidedabai** [AppleClash/App#9]
不好意思，问题已解决，文件读取的问题

**Comment by Arror** [comment]
> 因为不熟悉swiftui，所以我普通的Swift和OC重写你的实现，但我发现处于连接中的状态，检查了各种配置，发现并没有问题，甚至替换到你的代码中，就可以正常连接，懵逼状态

可以看看日志，连接是否建立，如果已经建立，那可能是UI状态没做对。
提供的信息太少了，无法准确判断。
